require("./compat/date");
require("./compat/style");
require("./core/selection-attr");
require("./core/selection-classed");
require("./core/selection-style");
require("./core/selection-property");
require("./core/selection-text");
require("./core/selection-html");
require("./core/selection-append");
require("./core/selection-insert");
require("./core/selection-remove");
require("./core/selection-data");
require("./core/selection-datum");
require("./core/selection-order");
require("./core/selection-sort");
require("./core/selection-on");
require("./core/selection-call");
require("./core/selection-empty");
require("./core/selection-node");
require("./core/selection-transition");
require("./core/selection-enter-select");
require("./core/transition-select");
require("./core/transition-selectAll");
require("./core/transition-filter");
require("./core/transition-attr");
require("./core/transition-style");
require("./core/transition-text");
require("./core/transition-remove");
require("./core/transition-ease");
require("./core/transition-delay");
require("./core/transition-duration");
require("./core/transition-each");
require("./core/transition-transition");

var d3 = require("./core/core"),
    interpolate = require("./core/interpolate"),
    bisect = require("./core/bisect");
d3.map = require("./core/map");
d3.functor = require("./core/functor");
d3.rebind = require("./core/rebind");
d3.ascending = require("./core/ascending");
d3.descending = require("./core/descending");
d3.mean = require("./core/mean");
d3.median = require("./core/median");
d3.min = require("./core/min");
d3.max = require("./core/max");
d3.extent = require("./core/extent");
d3.random = require("./core/random");
d3.sum = require("./core/sum");
d3.quantile = require("./core/quantile");
d3.shuffle = require("./core/shuffle");
d3.transpose = require("./core/transpose");
d3.zip = require("./core/zip");
d3.bisect = bisect;
d3.bisector = bisect.or;
d3.bisectLeft = bisect.left;
d3.bisectRight = bisect.right;
d3.nest = require("./core/nest");
d3.keys = require("./core/keys");
d3.values = require("./core/values");
d3.entries = require("./core/entries");
d3.permute = require("./core/permute");
d3.merge = require("./core/merge");
d3.range = require("./core/range");
d3.requote = require("./core/requote");
d3.round = require("./core/round");
d3.xhr = require("./core/xhr");
d3.text = require("./core/text");
d3.json = require("./core/json");
d3.html = require("./core/html");
d3.xml = require("./core/xml");
d3.ns = require("./core/ns");
d3.dispatch = require("./core/dispatch");
d3.format = require("./core/format");
d3.formatPrefix = require("./core/formatPrefix");
d3.ease = require("./core/ease");
d3.transform = require("./core/transform");
d3.interpolate = interpolate;
d3.interpolators = interpolate.interpolators;
d3.interpolateRgb = interpolate.rgb;
d3.interpolateLab = interpolate.lab;
d3.interpolateHcl = interpolate.hcl;
d3.interpolateHsl = interpolate.hsl;
d3.interpolateRound = interpolate.round;
d3.interpolateArray = interpolate.array;
d3.interpolateString = interpolate.string;
d3.interpolateNumber = interpolate.number;
d3.interpolateObject = interpolate.object;
d3.interpolateTransform = interpolate.transform;
d3.rgb = require("./core/rgb");
d3.hsl = require("./core/hsl");
d3.hcl = require("./core/hcl");
d3.lab = require("./core/lab");
d3.selection = require("./core/selection");
d3.select = require("./core/selection-root");
d3.selectAll = require("./core/selection-root").all;
d3.selection.enter = require("./core/selection-enter");
d3.transition = require("./core/transition");
d3.timer = require("./core/timer");
d3.mouse = require("./core/mouse");
d3.touches = require("./core/touches");
module.exports = d3;